Update and rename blank.yml to 13R.yml

diff --git a/.github/workflows/13R.yml b/.github/workflows/13R.yml
--- a/.github/workflows/13R.yml
+++ b/.github/workflows/13R.yml
@@ -1,4 +1,4 @@
-name: 13R
+name: Build OnePlus 13R
 
 on:
   workflow_dispatch:
@@ -126,6 +126,7 @@ jobs:
         run: |
           cd kernel_workspace
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-5.15
+          git clone https://github.com/ShirkNeko/SukiSU_patch.git
           git clone https://github.com/WildKernels/OnePlus_KernelSU_SUSFS.git
           cd kernel_platform
           echo "Applying SUSFS patches"
@@ -133,12 +134,24 @@ jobs:
           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           cd ./common
-          patch -p1 < 50_add_susfs_in_gki-android14-5.15.patch || true
-          echo "SUSFS patch applied"
-          cp ../../WildKernels/OnePlus_KernelSU_SUSFS/69_hide_stuff.patch ./
+          if patch -p1 --dry-run < 50_add_susfs_in_gki-android14-5.15.patch; then
+            patch -p1 < 50_add_susfs_in_gki-android14-5.15.patch
+            echo "SUSFS patch applied successfully"
+          else
+            echo "SUSFS patch failed to apply cleanly, check .rej files for details"
+            patch -p1 < 50_add_susfs_in_gki-android14-5.15.patch || true
+            find . -name "*.rej" -exec echo "Rejected hunk in {}" \;
+            exit 1
+          fi
+          cp ../../SukiSU_patch/69_hide_stuff.patch ./
           echo "Applying hide stuff patch"
-          patch -p1 -F 3 < 69_hide_stuff.patch
-          echo "Hide stuff patch applied"
+          if patch -p1 --dry-run -F 3 < 69_hide_stuff.patch; then
+            patch -p1 -F 3 < 69_hide_stuff.patch
+            echo "Hide stuff patch applied successfully"
+          else
+            echo "Hide stuff patch failed to apply, skipping"
+            exit 1
+          fi
 
       - name: Apply VFS
         if: ${{ github.event.inputs.VFS == 'true' }}
@@ -146,8 +159,13 @@ jobs:
           cd kernel_workspace/kernel_platform/common
           cp ../../WildKernels/OnePlus_KernelSU_SUSFS/hooks/syscall_hooks.patch ./
           echo "Applying VFS patch"
-          patch -p1 -F 3 < syscall_hooks.patch
-          echo "VFS patch applied"
+          if patch -p1 --dry-run -F 3 < syscall_hooks.patch; then
+            patch -p1 -F 3 < syscall_hooks.patch
+            echo "VFS patch applied successfully"
+          else
+            echo "VFS patch failed to apply, check .rej files for details"
+            exit 1
+          fi
 
       - name: Apply LZ4KD
         if: ${{ github.event.inputs.ZRAM == 'true' }}
@@ -155,12 +173,22 @@ jobs:
           cd kernel_workspace/kernel_platform/common
           cp ../../WildKernels/OnePlus_KernelSU_SUSFS/other/zram/zram_patch/5.15/lz4kd.patch ./
           echo "Applying LZ4KD patch"
-          patch -p1 -F 3 < lz4kd.patch || true
-          echo "LZ4KD patch applied"
+          if patch -p1 --dry-run -F 3 < lz4kd.patch; then
+            patch -p1 -F 3 < lz4kd.patch
+            echo "LZ4KD patch applied successfully"
+          else
+            echo "LZ4KD patch failed to apply, check .rej files for details"
+            exit 1
+          fi
           cp ../../WildKernels/OnePlus_KernelSU_SUSFS/other/zram/zram_patch/5.15/lz4k_oplus.patch ./
           echo "Applying LZ4K OPlus patch"
-          patch -p1 -F 3 < lz4k_oplus.patch || true
-          echo "LZ4K OPlus patch applied"
+          if patch -p1 --dry-run -F 3 < lz4k_oplus.patch; then
+            patch -p1 -F 3 < lz4k_oplus.patch
+            echo "LZ4K OPlus patch applied successfully"
+          else
+            echo "LZ4K OPlus patch failed to apply, check .rej files for details"
+            exit 1
+          fi
 
       - name: Add Configuration Settings
         run: |
@@ -168,6 +196,8 @@ jobs:
           CONFIG_FILE=./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU=y" >> "$CONFIG_FILE"
           echo "CONFIG_KPM=y" >> "$CONFIG_FILE"
+          echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG_FILE"
+          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$CONFIG_FILE"
           if [ "${{ github.event.inputs.VFS }}" = "false" ]; then
             echo "CONFIG_KPROBES=y" >> "$CONFIG_FILE"
             echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> "$CONFIG_FILE"
@@ -203,6 +233,50 @@ jobs:
             echo "CONFIG_MODULE_SIG=n" >> "$CONFIG_FILE"
           fi
           sed -i 's/check_defconfig//' ./common/build.config.gki
+
+      - name: 😋Add BBR Support
+        run: |
+          echo "Changing to configuration directory: kernel_workspace..."
+          cd kernel_workspace/kernel_platform
+          echo "Adding BBR configuration settings to gki_defconfig..."
+          echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DEFAULT_TCP_CONG=\"bbr\"" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_TCP_CONG_CDG=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DEFAULT_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DEFAULT_CUBIC=n" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DEFAULT_CDG=n" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_NET_SCH_DEFAULT=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DEFAULT_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo 'CONFIG_DEFAULT_NET_SCH="fq"' >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_NET_SCH_SFQ=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_NET_SCH_FQ_CODEL=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_NET_SCH_TBF=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_TCP_CONG_HTCP=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_IP_NF_TARGET_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_IP_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_TCP_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_IPV6_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
+
+      - name: 😋Add TTL Target Support
+        run: |
+          echo "Changing to configuration directory: kernel_workspace..."
+          cd kernel_workspace/kernel_platform
+          echo "Adding TTL configuration settings to gki_defconfig..."
+          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
+
+      - name: 🎶Disable Debug stuffs
+        run: |
+          echo "Changing to configuration directory: kernel_workspace..."
+          cd kernel_workspace/kernel_platform
+          echo "Disabling debug configurations in gki_defconfig..."
+          echo "CONFIG_DEBUG_KERNEL=n" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DYNAMIC_DEBUG=n" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_DEBUG_INFO=n" >> ./common/arch/arm64/configs/gki_defconfig
 
       - name: Build kernel
         run: |
